### ISSUE TITLE
link/rendering bug when authors != maintainers

### ISSUE THREAD

**Issue by WillClinger** [ashinn/snow-fort#1]
The "Authors" column went a little haywire when I uploaded packages using both the `--authors` and `--maintainers` options.  The `package.scm` file looks okay, so I think this is just a bug in the conversion to HTML.

**Comment by ashinn** [comment]
Yep, this was a bug in regexp-replace for non-ascii inputs - thanks Taylan for having a funny name!
Fixed.

**Comment by wasamasa** [comment]
If this has been fixed, the issue should be closed as well.

**Comment by ashinn** [comment]
Double checked, there was a lingering bug in not including space between authors names, fixed.
